# Generated by Django 3.1.5 on 2021-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='분류')),
                ('name', models.CharField(max_length=32, verbose_name='물품명')),
                ('date', models.CharField(max_length=30, verbose_name='습득날짜')),
                ('image', models.ImageField(help_text='파일 형식은 jpg 또는 png로, 사이즈는 가로 1,240px, 세로 930px 이상으로 올려주세요.', upload_to='images/found/%Y/%m', verbose_name='물품사진')),
                ('contact', models.CharField(max_length=15, verbose_name='연락처')),
                ('description', models.TextField(verbose_name='상세설명')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '습득물',
                'verbose_name_plural': '습득물들',
                'db_table': 'Input_Found_list',
                'ordering': ('-registered_date',),
            },
        ),
        migrations.CreateModel(
            name='Lost_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='분류')),
                ('name', models.CharField(max_length=32, verbose_name='물품명')),
                ('date', models.CharField(max_length=32, verbose_name='분실날짜')),
                ('money', models.CharField(max_length=255, verbose_name='사례금')),
                ('image', models.ImageField(upload_to='images/lost/%Y/%m')),
                ('contact', models.CharField(max_length=13, verbose_name='연락처')),
                ('description', models.TextField(verbose_name='상세설명')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '분실물',
                'verbose_name_plural': '분실물',
                'db_table': 'Input_Lost_list',
                'ordering': ('-registered_date',),
            },
        ),
    ]
